# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App 

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:  
  APP_NAME: testing-pck-blazorapp
  DOCKER_API_TAG: testapp
  PUBLISH_PROFILE: ${{ secrets.PUBLISH_PROFILE_TESTAPP }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  
  REGISTRY_URL: https://testigpckcr.azurecr.io/
  REGISTRY_NAME: testigpckcr.azurecr.io/testigpckcr
  REGISTRY_USERNAME: testigpckcr
  
  ENVIROMENT_NAME: Development

jobs:

  build:
    runs-on: "ubuntu-latest"
    timeout-minutes: 15 
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Build and push ${{ env.DOCKER_API_TAG }} container image to registry
        uses: docker/build-push-action@v3
        with:
          context: ./BlazorApp
          push: true
          tags: ${{ env.REGISTRY_NAME }}/${{ env.DOCKER_API_TAG }}:${{ github.sha }}
          file: ./BlazorApp/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - id: deploy-to-webapp
        name: Deploy ${{ env.DOCKER_API_TAG }} to ${{ env.ENVIROMENT_NAME }}
        uses: azure/webapps-deploy@v2
        with:
          app-name: "${{ env.APP_NAME}}"
          slot-name: "production"
          publish-profile: ${{ env.PUBLISH_PROFILE }}
          images: "${{ env.REGISTRY_NAME }}/${{ env.DOCKER_API_TAG }}:${{ github.sha }}"
